### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by lansana** [dancancro/great-big-example-application#105]
Can you please explain why you made the decision to put all of the Angular config files in the root of the project as opposed to in the root of your `webapp` directory? It seems to me that choice would not scale as you add more and more UI's or other microservices, when each of them also needs their own configuration files. It would start to grow very rapidly and become a mess.

Wouldn't a better approach be to keep it how it is when generating a new Angular app with the Angular CLI, and to keep the project root for global config?

I just noticed this when I was looking for your `package.json` in `webapp` (which is where I assumed it was), but apparently not.

I could be wrong. Just curious.

**Comment by dancancro** [comment]
Hi @lansana I didn't make that decision. That's just how JHipster projects [are organized](https://github.com/jhipster/generator-jhipster/tree/master/generators/client/templates/angular). You might be able to get an answer on the [JHipster Gitter](https://gitter.im/jhipster/generator-jhipster) or with a [JHipster issue](https://github.com/jhipster/generator-jhipster/issues). I've had a few questions about JHipster file structure decisions too but changing JHipster hasn't been a top priority for me. Keeping things the way they are does help make upgrading JHipster code less painful.

I started a [nativescript](https://github.com/NathanWalker/angular-seed-advanced) branch based on [this](https://github.com/NathanWalker/angular-seed-advanced) but haven't spent much time on it. That will be my first exploration into alternative UIs so I'll probably give it more priority then. Feel free to take a crack at it if you want. The contributor list is not at all crowded yet :)

**Comment by lansana** [comment]
Ah I see, thanks for the clarification! I may add a contribution then :) I was working on a similar repo for Go/Angular 2 and your structure choices has helped me a lot, especially some of the Java "clean architecture" and the Angular stuff. Learning a lot reading through your code, thanks!
