### ISSUE TITLE
Add meals demo

### ISSUE THREAD

**Issue by dancancro** [dancancro/great-big-example-application#142]
This demo has a lot of tests, offline mode, and firebase integration.

Source: https://github.com/adriancarriger/clean-to-the-core
Branch: https://github.com/dancancro/great-big-example-application/tree/meals

Stall:
I haven't been able to isolate the layout and styles, including bootstrap, used in the rest of the app, from the ones used by this feature. I last tried removing the global and vendor sass files creating a separate layout component for each,  and putting each's sass inside a my-layout {} to try to encapsulate it, but that didn't quite work. I think each subcomponent's sass needs to be tweaked so it doesn't use the single set of styles in `theme/`. I started looking at the approach of a wrapbootstrap [template](https://wrapbootstrap.com/theme/angle-bootstrap-admin-template-WB04HF123) with multiple themes, and then got discouraged because what they are selling for lunch money is so much more impressive than what's taking me ages to make. Need to take a break.

**Comment by wilsonmar** [comment]
Dan, what techniques does this app demostrate?

**Comment by dancancro** [comment]
From its [GitHub page](https://github.com/adriancarriger/clean-to-the-core#features), it does this:

- offline: Works offline even after a full page refresh using a service worker. Subsequent page load times are very fast on browsers that support service workers.
- accessible: Designed to be accessible and passes the chrome accessibility extension audit
- notifications: Uses push notifications to inform a user when a recipe timer is complete
- lazy routes: Routes are lazy loaded for a faster initial load time

It also demonstrates infinite scroll and a professionally styled, mobile-friendly UI.

**Comment by dancancro** [comment]
A few bugs left to fix but good enough for government work.
