### ISSUE TITLE
copy-webpack-plugin] unable to locate './node_modules/swagger-ui/dist/css

### ISSUE THREAD

**Issue by koyaja** [dancancro/great-big-example-application#184]
I tried to integrate the project in my project, it does not take the appearance of the theme of ng2-admin and I have this error
`ERROR in [copy-webpack-plugin] unable to locate './node_modules/swagger-ui/dist/css' at 'C:\Users\SOFT IT\Documents\GitHub\HotMan\node_modules\swagger-ui\dist\css'

ERROR in [copy-webpack-plugin] unable to locate './node_modules/swagger-ui/dist/lib' at 'C:\Users\SOFT IT\Documents\GitHub\HotMan\node_modules\swagger-ui\dist\lib'

ERROR in [copy-webpack-plugin] unable to locate './node_modules/swagger-ui/dist/swagger-ui.min.js' at 'C:\Users\SOFT IT\Documents\GitHub\HotMan\node_modules\swagger-ui\dist\swagger-u
i.min.js'`

**Comment by dancancro** [comment]
I've been grappling with what to do about themes and styles for a while now. I want this to emulate a real app. So it probably shouldn't have ten different css libraries and themes. But it would also be nice if things looked in this project the way they look in the source projects.

I recently took a position on it and decided to try to use only one theme for the whole application and let the parts not look exactly the way they do in the source projects, at least without redoing things to make them look the same. Function trumps form until I get better as sass modularization.

So if you're using a recent copy and the blue ng2-admin background isn't there, then this is why. It was looking like a big deal to support multiple sets of global style rules each for a different screen of the app.

I came across the swagger-ui problem and thought I fixed it. I didn't get that error before pushing to the master branch. In any event, I see a change in the "meals" branch that handled it. Look at this part of [webpack.common.js](https://github.com/dancancro/great-big-example-application/blob/meals/webpack/webpack.common.js#L92-L96) 
```
// { from: './node_modules/swagger-ui/dist/css', to: 'swagger-ui/dist/
// { from: './node_modules/swagger-ui/dist/lib', to: 'swagger-ui/dist/lib' },
// { from: './node_modules/swagger-ui/dist/swagger-ui.min.js', to: 'swagger-ui/dist/swagger-ui.min.
{ from: './node_modules/swagger-ui/dist/swagger-ui.css', to: 'swagger-ui/dist/swagger-ui.
{ from: './node_modules/swagger-ui/dist/swagger-ui.js', to: 'swagger-ui/dist/swagger-ui.js' },
```
You just need to look into your node_modules directory and fix the paths a little.

**Comment by koyaja** [comment]
Thanks i solved the problem swagger, now how i give the appearance of ng2-admin despite that i put
`<main baThemeRun>
<jhi-page-ribbon></jhi-page-ribbon>
<div>
    <router-outlet name="navbar"></router-outlet>
</div>
<div class="container-fluid">
    <div class="card jh-card">
        <router-outlet></router-outlet>
        <router-outlet name="popup"></router-outlet>
    </div>
    <jhi-footer></jhi-footer>
</div>
</main>`

**Comment by dancancro** [comment]
It has all to do with styles, not the main component template. If you set global style to make the dashboard page look like it does in ng2-admin, then the rest of the application will be affected and have white text on white background and whatnot. So, you'll need to play with styles more than I was willing to play with styles in order to get everything to work right.

**Comment by koyaja** [comment]
thank I will play on the style if it does not work I come back to you I have to import `@import 'conf/conf';` in my gloale.scss but it does not work

**Comment by satishpatro44** [comment]
I checked the webpack-common.js
 `new CopyWebpackPlugin(
  [
            { from: './node_modules/swagger-ui/dist/css', to: 'swagger-ui/dist/css' },
            { from: './node_modules/swagger-ui/dist/lib', to: 'swagger-ui/dist/lib' }...
`
And I checked github of swagger-ui, there is no folder of css & lib in swagger-ui/dist

**Comment by satishpatro44** [comment]
@dancancro look at this

**Comment by Caltalys** [comment]
You can downgrade swagger-ui dependency from 3.22 to 2.2.10. It's ok with me
