### ISSUE TITLE
Why you use RouterModule.forRoot(...) in all modules?

### ISSUE THREAD

**Issue by kolkov** [dancancro/great-big-example-application#185]
Hi!
For what reason do you use `RouterModule.forRoot(...)` in all modules, and not just in the main?

![image](https://user-images.githubusercontent.com/3740898/29068082-ef2cf294-7c3d-11e7-94b9-02bea302ae77.png)

**Comment by dancancro** [comment]
That practice came from [jhipster](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/app/home/_home.module.ts#L29). 

From the [Angular docs](https://angular.io/api/router/RouterModule#how-to-use) it looks like the only difference between them is that `forRoot` includes the Router service. You're right that it seems we [should use](https://angular.io/guide/router#hero-feature-route-configuration) `.forChild`. It's not that clear why though
> Only call RouterModule.forRoot in the root AppRoutingModule (or the AppModule if that's where you register top level application routes). In any other module, you must call the RouterModule.forChild method to register additional routes.

[I asked](https://gitter.im/jhipster/generator-jhipster?at=5989de0f51915d962af78a5b) on JHipster's Gitter. Maybe someone else knows.
