### ISSUE TITLE
Remove redundant StoreModule.forRoot call in app.module

### ISSUE THREAD

**Issue by rob3c** [dancancro/great-big-example-application#186]
`StoreModule.forRoot(reducers, { metaReducers })` is called twice in succession in "src/main/webapp/app/app.module.ts"

**Comment by dancancro** [comment]
Thanks! With all the mashing together of examples I've been doing lately, I've committed a few duplications of this sort. I'm surprised that they haven't seemed to cause any problems as far as I can tell.
