### ISSUE TITLE
Incorrectly Importing RxJS 

### ISSUE THREAD

**Issue by moshejs** [dancancro/great-big-example-application#191]
According to this article: https://christianliebel.com/2017/07/import-rxjs-correctly/ the author claims that RxJS is "polyfill-like" and is better to import it from a file called "rxjs-imports.ts." This will require some work, so I considered opening an issue before I contribute.

Thanks.

**Comment by dancancro** [comment]
That looks pretty cool. It seems that you would just need to add a few lines to tslint.json, find all the operators used in the application and put them in the new imports file and then run the linter and remove them from where they were. Right?

**Comment by moshejs** [comment]
Sounds about right, working on it
