### ISSUE TITLE
Could not find Angular Material Core theme

### ISSUE THREAD

**Issue by moshejs** [dancancro/great-big-example-application#193]
Running "ng test", I see the following output:

WARN: 'Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming'
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 66 of 178 SUCCESS (0 secs / 4.333 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 92 of 178 SUCCESS (0 secs / 8.112 secs)
.
WARN: 'Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming'
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 92 of 178 SUCCESS (0 secs / 8.112 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 93 of 178 SUCCESS (0 secs / 8.822 secs)
.
WARN: 'Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming'
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 93 of 178 SUCCESS (0 secs / 8.822 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 94 of 178 SUCCESS (0 secs / 9.545 secs)
.
WARN: 'Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming'
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 94 of 178 SUCCESS (0 secs / 9.545 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 95 of 178 SUCCESS (0 secs / 10.276 secs)
.
WARN: 'Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming'
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 95 of 178 SUCCESS (0 secs / 10.276 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 96 of 178 SUCCESS (0 secs / 11.032 secs)
.
WARN: 'Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming'
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 96 of 178 SUCCESS (0 secs / 11.032 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 175 of 178 SUCCESS (0 secs / 17.483 secs)
 PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 178 of 178 SUCCESS (0 secs / 17.514 secs)

Not a big deal, but I could probably fix this

**Comment by dancancro** [comment]
Cool. CSS is not my forté and I haven't figured out how to use both Bootstrap and Material Design in the same application. So I was just living with it. But if it's easy, feel free to fix it.

**Comment by moshejs** [comment]
Material and (jQuery/Bootstrap) is an anti-pattern, however, I had a starter theme which was opened sourced recently: https://github.com/lokra/ui-starter

Anyways, he used bootstrap with material together (I've had bugs, but it works fine.) It might help to expand the project if I could incorporate this theme's elements here if I just knew where to plug them in :)

**Comment by dancancro** [comment]
That looks amazing. Electron would be a popular addition too. I started adding some of the ng2admin theme, but I'm completely neutral about them. At this point I'm mostly wondering whether combining bootstrap and material is a normal thing to do in real life. I don't really want this app to show people how to do things that professionals don't do. On the other hand, I want it to demonstrate all the common things, and material and bootstrap are both common. How does this one use them together? Are they both used on the same page or do some pages use only bootstrap and some only material? If it's the second one, then that sounds like a winner. If it's the first, then I'd wonder how normal that is. Let's chat. I'll try to explain what I know about how styles are working at the moment.

**Comment by dancancro** [comment]
Closed with https://github.com/dancancro/great-big-example-application/commit/da3d500816bfd27dccb52a629357f8240895d280
